<?php

namespace Probesys\Bundle\PostBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostMetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostMetaRepository extends EntityRepository
{
    public function findByPostId($postId)
    {
        $dql = 'SELECT m
                FROM ProbesysPostBundle:PostMeta: m
                WHERE m.post = :postId
                ';

        $q = $this->_em->createQuery($dql);

        $q->setParameter('post', $postId);

        return $q->getResult();
    }
}
