<?php

namespace Probesys\Bundle\PostBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    private $post_content;

    public function getPostContent()
    {
        return TRUE;
    }
}
