<?php

namespace Probesys\Bundle\PostBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    // public function setMeta($key, $value)
    // {
    //     return TRUE;
    // }
    //

    // public function getPostMeta()
    // {
    //     return "toto2";
    // }
    //
    //

    public function getPostMetaByMetaKey($metaKey)
    {

        // return $this->getEntityManager()
        //     ->createQuery(
        //         'SELECT m
        //         FROM ProbesysPostBundle:PostMeta m
        //         ASC'
        //     )
        //     ->getResult();


        // $postMeta = "";

        return $this->id;
    }
}
